### PR TITLE
Add dashboard mpi

### PR DESCRIPTION
**Pull request by cheng-tan**

### CODE REVIEW

**Comment by marco-rossi29** [comment]
I see that dashboard.py contains many functions from ds_parse.py. There is an issue of code duplication. In particular if our dsjson format changes in the future, ideally we should have only one place to change.

To solve this issue, can you import ds_parse and avoid duplication?

**Comment by marco-rossi29** [comment]
If importing ds_parse is feasible. Could we also import dashboard_utils.py to basically remove the need for dashboard.py?

**Comment by cheng-tan** [comment]
ds_parse is used by dashboard_util, no need to import anymore.

**Comment by ataymano** [comment]
SInce we are going to use it more actively very soon, can we check it in and fix remaining issues afterwards in separate prs (right now no one except @cheng-tan can work on this code)?

**Comment by marco-rossi29** [comment]
@ataymano There are conflicts that must be resolved before merging

**Comment by cheng-tan** [comment]
Resubmitting a PR for dashboard mpi

**Pull request merged**
